name: analyze

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4.1.1
      - name: Analyze package
        uses: axel-op/dart-package-analyzer@stable
        with:
          githubToken: ${{secrets.GITHUB_TOKEN}}
