name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dart:stable
    steps:
    - name: Git checkout
      uses: actions/checkout@v4.1.1
    - name: Install dependencies
      run: dart pub get
    - name: Install coverage tool
      run: dart pub global activate coverage
    - name: Run tests with coverage
      run: dart pub global run coverage:test_with_coverage
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: coverage/lcov.info
